// ---------------------------------------------
// ------ CREATION DE LA LISTE DE COOKIES ------
// ---------------------------------------------

// Blank cookie space
// {
//     img: "",
//     nom: "",
//     gender: "",
//     role: "",
//     position: "",
//     element: "",
//     rarity: "",
//     release: "",
//     quote: "Aaaaah!!!!",
//    skill: "GingerbraveSkill",

const cookies = [
  // -----------------------------------------------------------------------------------------------------------------------
  // -------------------------------------------------------- WITCH --------------------------------------------------------
  // -----------------------------------------------------------------------------------------------------------------------

  {
    img: "DarkEnchantressCookie",
    nom: "Dark Enchantress Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Chaos",
    rarity: "Witch",
    release: "7.0",
    quote: "You know NOTHING of the world's truth!",
    skill: "DarkEnchantressCookieSkill",
  },

  // -----------------------------------------------------------------------------------------------------------------------
  // -------------------------------------------------------- BEAST --------------------------------------------------------
  // -----------------------------------------------------------------------------------------------------------------------

  {
    img: "EternalSugarCookie",
    nom: "Eternal Sugar Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Poison",
    rarity: "Beast",
    release: "6.4",
    quote: "Cookies are such lovely creatures!",
    skill: "EternalSugarCookieSkill",
  },
  {
    img: "BurningSpiceCookie",
    nom: "Burning Spice Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Fire",
    rarity: "Beast",
    release: "5.10",
    quote: "You there, entertain me!",
    skill: "BurningSpiceCookieSkill",
  },
  {
    img: "MysticFlourCookie",
    nom: "Mystic Flour Cookie",
    gender: "She / Her",
    role: "Healing",
    position: "Rear",
    element: "None",
    rarity: "Beast",
    release: "5.5",
    quote: "What causes you to suffer?",
    skill: "MysticFlourCookieSkill",
  },
  {
    img: "ShadowMilkCookie",
    nom: "Shadow Milk Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "None",
    rarity: "Beast",
    release: "6.0",
    quote: "Aw, don't be a drag! C'mon, have some fun!",
    skill: "ShadowMilkCookieSkill",
  },
  {
    img: "SilentSaltCookie",
    nom: "Silent Salt Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Front",
    element: "Darkness / Steel",
    rarity: "Beast",
    release: "6.9",
    quote: "Simply a means to an end...",
    skill: "SilentSaltCookieSkill",
  },

  // -----------------------------------------------------------------------------------------------------------------------
  // ------------------------------------------------------- ANCIENT -------------------------------------------------------
  // -----------------------------------------------------------------------------------------------------------------------

  {
    img: "GoldenCheeseCookie",
    nom: "Golden Cheese Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Middle",
    element: "Earth",
    rarity: "Ancient",
    release: "4.11",
    quote: "How pathetic!",
    skill: "GoldenCheeseCookieSkill",
  },
  {
    img: "GoldenCheeseAwakenedCookie",
    nom: "Golden Cheese Cookie (Immortal)",
    gender: "She / Her",
    role: "Ranged",
    position: "Middle",
    element: "Earth",
    rarity: "Ancient",
    release: "5.11",
    quote: "My desires WILL be FULFILLED!",
    skill: "GoldenCheeseAwakenedCookieSkill",
  },
  {
    img: "PureVanillaCookie",
    nom: "Pure Vanilla Cookie",
    gender: "He / Him",
    role: "Healing",
    position: "Rear",
    element: "None",
    rarity: "Ancient",
    release: "1.3",
    quote: "All Cookies shall be happy!",
    skill: "PureVanillaCookieSkill",
  },
  {
    img: "PureVanillaAwakenedCookie",
    nom: "Pure Vanilla Cookie (Compassionate)",
    gender: "He / Him",
    role: "Healing",
    position: "Rear",
    element: "Light",
    rarity: "Ancient",
    release: "6.1",
    quote: "I will always try my hardest... for everyone.",
    skill: "PureVanillaAwakenedCookieSkill",
  },
  {
    img: "HollyberryCookie",
    nom: "Hollyberry Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Ancient",
    release: "2.0",
    quote: "I'll be a hero my descendants are proud of!",
    skill: "HollyberryCookieSkill",
  },
  {
    img: "HollyberryAwakenedCookie",
    nom: "Hollyberry Cookie (Aegis)",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Ancient",
    release: "6.5",
    quote: "I hear the triumphant cries!",
    skill: "HollyberryAwakenedCookieSkill",
  },
  {
    img: "DarkCacaoCookie",
    nom: "Dark Cacao Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Darkness / Electricity",
    rarity: "Ancient",
    release: "2.7",
    quote: "Some wishes are not meant to come true...",
    skill: "DarkCacaoCookieSkill",
  },
  {
    img: "DarkCacaoAwakenedCookie",
    nom: "Dark Cacao Cookie (Dragon Lord)",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Darkness",
    rarity: "Ancient",
    release: "5.6",
    quote: "The past full of regrets is now behind me.",
    skill: "DarkCacaoAwakenedCookieSkill",
  },
  {
    img: "WhiteLilyCookie",
    nom: "White Lily Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Grass",
    rarity: "Ancient",
    release: "5.0",
    quote: "I... I'm sorry for asking...",
    skill: "WhiteLilyCookieSkill",
  },
  {
    img: "WhiteLilyAwakenedCookie",
    nom: "White Lily Cookie (Dawnbringer)",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Grass",
    rarity: "Ancient",
    release: "6.10",
    quote: "Only I can stop myself.",
    skill: "WhiteLilyAwakenedCookieSkill",
  },

  // -----------------------------------------------------------------------------------------------------------------------
  // ------------------------------------------------------ LEGENDARY ------------------------------------------------------
  // -----------------------------------------------------------------------------------------------------------------------

  {
    img: "SugarSwanCookie",
    nom: "Sugar Swan Cookie",
    gender: "She / It",
    role: "Healing",
    position: "Rear",
    element: "Light",
    rarity: "Legendary",
    release: "7.2",
    quote: "Even shadows follow my will.",
    skill: "SugarSwanCookieSkill",
  },

  {
    img: "MillennialTreeCookie",
    nom: "Millennial Tree Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Front",
    element: "Grass",
    rarity: "Legendary",
    release: "6.12",
    quote: "Darkness is but a drop in the ocean of Time...",
    skill: "MillennialTreeCookieSkill",
  },

  {
    img: "FireSpiritCookie",
    nom: "Fire Spirit Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Rear",
    element: "Fire",
    rarity: "Legendary",
    release: "6.3",
    quote: "Is this when I laugh like a villain? Ha ha!",
    skill: "FireSpiritCookieSkill",
  },

  {
    img: "WindArcherCookie",
    nom: "Wind Archer Cookie",
    gender: "He / Him",
    role: "Ranged",
    position: "Rear",
    element: "Wind",
    rarity: "Legendary",
    release: "5.9",
    quote: "The forest calls for it.",
    skill: "WindArcherCookieSkill",
  },

  {
    img: "StormbringerCookie",
    nom: "Stormbringer Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "Electricity",
    rarity: "Legendary",
    release: "5.4",
    quote: "I rule over all that exists!",
    skill: "StormbringerCookieSkill",
  },

  {
    img: "MoonlightCookie",
    nom: "Moonlight Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "None",
    rarity: "Legendary",
    release: "4.0",
    quote: "May there never be a day when we miss this moment...",
    skill: "MoonlightCookieSkill",
  },

  {
    img: "BlackPearlCookie",
    nom: "Black Pearl Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Middle",
    element: "Water",
    rarity: "Legendary",
    release: "3.6",
    quote: "Cookies are small, sweet... repulsive abominations!",
    skill: "BlackPearlCookieSkill",
  },

  {
    img: "FrostQueenCookie",
    nom: "Frost Queen Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Ice",
    rarity: "Legendary",
    release: "2.4",
    quote: "Tis cold and silent... At last.",
    skill: "FrostQueenCookieSkill",
  },

  {
    img: "SeaFairyCookie",
    nom: "Sea Fairy Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Water",
    rarity: "Legendary",
    release: "1.6",
    quote: "May there never be a day when we regret this moment...",
    skill: "SeaFairyCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // ------------------------------------------------------- DRAGON -------------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------

  {
    img: "PitayaDragonCookie",
    nom: "Pitaya Dragon Cookie",
    gender: "They / It",
    role: "Charge",
    position: "Front",
    element: "Fire",
    rarity: "Dragon",
    release: "4.5",
    quote: "Cower before my true form!",
    skill: "PitayaDragonCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // ----------------------------------------------------- SUPER EPIC -----------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------

  {
    img: "VenomDoughCookie",
    nom: "Venom Dough Cookie",
    gender: "They / Them",
    role: "Bomber",
    position: "Rear",
    element: "Poison / Chaos",
    rarity: "Super Epic",
    release: "7.1",
    quote: "This peaceful sky seems... so foreign to me.",
    skill: "VenomDoughCookieSkill",
  },

  {
    img: "Doughael",
    nom: "Doughael",
    gender: "They / Them",
    role: "Healing",
    position: "Middle",
    element: "None",
    rarity: "Super Epic",
    release: "6.8",
    quote: "We were chosen to walk this path.",
    skill: "DoughaelSkill",
  },

  {
    img: "CamelliaCookie",
    nom: "Camellia Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Grass",
    rarity: "Super Epic",
    release: "5.12",
    quote: "Everything has a price!",
    skill: "CamelliaCookieSkill",
  },

  {
    img: "ElderFaerieCookie",
    nom: "Elder Faerie Cookie",
    gender: "He / Him",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Super Epic",
    release: "5.2",
    quote: "Stand back, spawns of evil!",
    skill: "ElderFaerieCookieSkill",
  },

  {
    img: "CrimsonCoralCookie",
    nom: "Crimson Coral Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Water",
    rarity: "Super Epic",
    release: "4.10",
    quote: "It's necessary for the kingdom.",
    skill: "CrimsonCoralCookieSkill",
  },

  {
    img: "ShiningGlitterCookie",
    nom: "Shining Glitter Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Electricity",
    rarity: "Super Epic",
    release: "4.7",
    quote: "There's always time for old friends.",
    skill: "ShiningGlitterCookieSkill",
  },

  {
    img: "CapsaicinCookie",
    nom: "Capsaicin Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Fire",
    rarity: "Super Epic",
    release: "4.3",
    quote: "I ain't losin' to some normies!",
    skill: "CapsaicinCookieSkill",
  },

  {
    img: "StardustCookie",
    nom: "Stardust Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "None",
    rarity: "Super Epic",
    release: "4.2",
    quote: "Do you accept me, despite having changed?",
    skill: "StardustCookieSkill",
  },

  {
    img: "SherbetCookie",
    nom: "Sherbet Cookie",
    gender: "He / Him",
    role: "Ranged",
    position: "Middle",
    element: "Ice",
    rarity: "Super Epic",
    release: "3.10",
    quote: "There is a Cookie who has been waiting for me...",
    skill: "SherbetCookieSkill",
  },

  {
    img: "OysterCookie",
    nom: "Oyster Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Super Epic",
    release: "3.2",
    quote: "Let's say this... is for peace.",
    skill: "OysterCookieSkill",
  },

  {
    img: "ClottedCreamCookie",
    nom: "Clotted Cream Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "Light",
    rarity: "Super Epic",
    release: "3.0",
    quote: "I pray my path is the righteous one.",
    skill: "ClottedCreamCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // -------------------------------------------------------- EPIC --------------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------

  {
    img: "PomPomDoughCookie",
    nom: "Pom-pom Dough Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Middle",
    element: "Poison / Chaos",
    rarity: "Epic",
    release: "7.1",
    quote: "Better run... While you can...",
    skill: "PomPomDoughCookieSkill",
  },

  {
    img: "MoldDoughCookie",
    nom: "Mold Dough Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Chaos",
    rarity: "Epic",
    release: "7.0",
    quote: "Star Jellies, huh. Delicious.",
    skill: "MoldDoughCookieSkill",
  },

  {
    img: "ChessChocoCookie",
    nom: "Chess Choco Cookie",
    gender: "They / Them",
    role: "Bomber",
    position: "Rear",
    element: "Chaos",
    rarity: "Epic",
    release: "6.11",
    quote: "We're a perfect team!",
    skill: "ChessChocoCookieSkill",
  },

  {
    img: "SaltCellarCookie",
    nom: "Salt Cellar Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "6.10",
    quote: "Prove your worth!",
    skill: "SaltCellarCookieSkill",
  },

  {
    img: "CharcoalCookie",
    nom: "Charcoal Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Rear",
    element: "Darkness",
    rarity: "Epic",
    release: "6.9",
    quote: "Chit-chat and laughter... Ain't used to this.",
    skill: "CharcoalCookieSkill",
  },

  {
    img: "MentholCookie",
    nom: "Menthol Cookie",
    gender: "He / Him",
    role: "Bomber",
    position: "Rear",
    element: "Water",
    rarity: "Epic",
    release: "6.8",
    quote: "We must make rational decisions even in times of turmoil.",
    skill: "MentholCookieSkill",
  },

  {
    img: "SeltzerCookie",
    nom: "Seltzer Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "Water",
    rarity: "Epic",
    release: "6.8",
    quote: "Oh gosh, oh gosh, OH GOSH!!!",
    skill: "SeltzerCookieSkill",
  },

  {
    img: "GrapefruitCookie",
    nom: "Grapefruit Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "Electricity",
    rarity: "Epic",
    release: "6.7",
    quote: "Psh, I guess I can take it!",
    skill: "GrapefruitCookieSkill",
  },

  {
    img: "ManjuCookie",
    nom: "Manju Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Rear",
    element: "Water",
    rarity: "Epic",
    release: "6.7",
    quote: "Ah-ah-ah! I won't take no for an answer!",
    skill: "ManjuCookieSkill",
  },

  {
    img: "JagaeCookie",
    nom: "Jagae Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Front",
    element: "Chaos",
    rarity: "Epic",
    release: "6.7",
    quote: "Time is money!",
    skill: "JagaeCookieSkill",
  },

  {
    img: "LimeCookie",
    nom: "Lime Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "6.7",
    quote: "Mighty... SPIKE!",
    skill: "LimeCookieSkill",
  },

  {
    img: "OrangeCookie",
    nom: "Orange Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Rear",
    element: "Electricity",
    rarity: "Epic",
    release: "6.6",
    quote: "Game, set, match!",
    skill: "OrangeCookieSkill",
  },

  {
    img: "LemonCookie",
    nom: "Lemon Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "Electricity",
    rarity: "Epic",
    release: "6.6",
    quote: "Mess with me and get electrified.",
    skill: "LemonCookieSkill",
  },

  {
    img: "CreamSodaCookie",
    nom: "Cream Soda Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "Water",
    rarity: "Epic",
    release: "6.5",
    quote: "I'm glad that so many of the students like me!",
    skill: "CreamSodaCookieSkill",
  },

  {
    img: "SugarflyCookie",
    nom: "Sugarfly Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "6.5",
    quote: "Careful with our sheep! They bite...",
    skill: "SugarflyCookieSkill",
  },

  {
    img: "PavlovaCookie",
    nom: "Pavlova Cookie",
    gender: "He / Him",
    role: "Ranged",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "6.4",
    quote: "... can I be free?",
    skill: "PavlovaCookieSkill",
  },

  {
    img: "AgarAgarCookie",
    nom: "Agar Agar Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Middle",
    element: "Fire / Electricity / Water / Wind / Ice",
    rarity: "Epic",
    release: "6.3",
    quote: "Something warm... Yes, that would be... nice...",
    skill: "AgarAgarCookieSkill",
  },

  {
    img: "WeddingCakeCookie",
    nom: "Wedding Cake Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "6.2",
    quote: "Anything to see the happy smiles!",
    skill: "WeddingCakeCookieSkill",
  },

  {
    img: "BlackForestCookie",
    nom: "Black Forest Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "6.2",
    quote: "What a blessed place... hu hu...",
    skill: "BlackForestCookieSkill",
  },

  {
    img: "BlackSapphireCookie",
    nom: "Black Sapphire Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Middle",
    element: "Poison",
    rarity: "Epic",
    release: "6.1",
    quote: "It's time to forget all your pains and worries!",
    skill: "BlackSapphireCookieSkill",
  },

  {
    img: "CandyAppleCookie",
    nom: "Candy Apple Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "6.0",
    quote: "Oh, the sweet, sweet taste of POWER!!!",
    skill: "CandyAppleCookieSkill",
  },

  {
    img: "OkshunCookie",
    nom: "Okshun Cookie",
    gender: "She / Her",
    role: "Healing",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "5.13",
    quote: "My dream is to explore the wide world!",
    skill: "OkshunCookieSkill",
  },

  {
    img: "GreenTeaMousseCookie",
    nom: "Green Tea Mousse Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Wind / Grass",
    rarity: "Epic",
    release: "5.13",
    quote: "Winner takes it all!",
    skill: "GreenTeaMousseCookieSkill",
  },

  {
    img: "PuddingALaModeCookie",
    nom: "Pudding à la Mode Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Rear",
    element: "Electricity",
    rarity: "Epic",
    release: "5.13",
    quote: "Sweetness at optimal level! Ready for battle!",
    skill: "PuddingALaModeCookieSkill",
  },

  {
    img: "ChocoDrizzleCookie",
    nom: "Choco Drizzle Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Middle",
    element: "Darkness",
    rarity: "Epic",
    release: "5.13",
    quote: "Don't dare look into the darkness.",
    skill: "ChocoDrizzleCookieSkill",
  },

  {
    img: "RedOsmanthusCookie",
    nom: "Red Osmanthus Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Middle",
    element: "Grass",
    rarity: "Epic",
    release: "5.12",
    quote: "Ooh, what a lovely melody!",
    skill: "RedOsmanthusCookieSkill",
  },

  {
    img: "GoldenOsmanthusCookie",
    nom: "Golden Osmanthus Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Grass",
    rarity: "Epic",
    release: "5.12",
    quote: "Time for an ingredient hunt!",
    skill: "GoldenOsmanthusCookieSkill",
  },

  {
    img: "SmokedCheeseCookie",
    nom: "Smoked Cheese Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Rear",
    element: "Earth",
    rarity: "Epic",
    release: "5.11",
    quote: "I'll do everything to prevent the nightmare from repeating.",
    skill: "SmokedCheeseCookieSkill",
  },

  {
    img: "NutmegTigerCookie",
    nom: "Nutmeg Tiger Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "Fire",
    rarity: "Epic",
    release: "5.10",
    quote: "Strength will make you complete!",
    skill: "NutmegTigerCookieSkill",
  },

  {
    img: "StarCoralCookie",
    nom: "Star Coral Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "5.8",
    quote: "Some stories are more than legends.",
    skill: "StarCoralCookieSkill",
  },

  {
    img: "PeachBlossomCookie",
    nom: "Peach Blossom Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "5.6",
    quote: "Sate your hunger in my garden.",
    skill: "PeachBlossomCookieSkill",
  },

  {
    img: "CloudHaetaeCookie",
    nom: "Cloud Haetae Cookie",
    gender: "They / Them",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "5.5",
    quote: "Hehe! Kneel before me!",
    skill: "CloudHaetaeCookieSkill",
  },

  {
    img: "StreetUrchinCookie",
    nom: "Street Urchin Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Fire",
    rarity: "Epic",
    release: "5.3",
    quote: "Maximum speed!",
    skill: "StreetUrchinCookieSkill",
  },

  {
    img: "CaramelChouxCookie",
    nom: "Caramel Choux Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "5.3",
    quote: "Things will never change unless you put in the work!",
    skill: "CaramelChouxCookieSkill",
  },

  {
    img: "ButterRollCookie",
    nom: "Butter Roll Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Steel / Chaos",
    rarity: "Epic",
    release: "5.2",
    quote: "Environment affects Cookies. Pretty cool, huh?",
    skill: "ButterRollCookieSkill",
  },

  {
    img: "MatchaCookie",
    nom: "Matcha Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Poison / Grass",
    rarity: "Epic",
    release: "5.2",
    quote: "He heh... Wouldn't you like to know...!",
    skill: "MatchaCookieSkill",
  },

  {
    img: "MercurialKnightCookie",
    nom: "Mercurial Knight Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "5.1",
    quote: "I shall fight until my very last breath.",
    skill: "MercurialKnightCookieSkill",
  },

  {
    img: "SilverbellCookie",
    nom: "Silverbell Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Rear",
    element: "Grass",
    rarity: "Epic",
    release: "5.0",
    quote: "One day, we all will become happy...!",
    skill: "SilverbellCookieSkill",
  },

  {
    img: "RebelCookie",
    nom: "Rebel Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Front",
    element: "Wind",
    rarity: "Epic",
    release: "4.16",
    quote: "I won't forgive the evil doings of those in power!",
    skill: "RebelCookieSkill",
  },

  {
    img: "LinzerCookie",
    nom: "Linzer Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "4.15",
    quote: "... Hm? My apologies. I was deeply absorbed in my work.",
    skill: "LinzerCookieSkill",
  },

  {
    img: "CremeBruleeCookie",
    nom: "Crème Brûlée Cookie",
    gender: "He / Him",
    role: "Ranged",
    position: "Rear",
    element: "Light",
    rarity: "Epic",
    release: "4.15",
    quote: "I've been told I'm talented ever since I was a child.",
    skill: "CremeBruleeCookieSkill",
  },

  {
    img: "OliveCookie",
    nom: "Olive Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "Earth / Fire / Electricity",
    rarity: "Epic",
    release: "4.13",
    quote: "Okie doke! All packed and ready to go!",
    skill: "OliveCookieSkill",
  },

  {
    img: "MozzarellaCookie",
    nom: "Mozzarella Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Earth",
    rarity: "Epic",
    release: "4.13",
    quote: "Time for some fun!",
    skill: "GMozzarellaCookieSkill",
  },

  {
    img: "FettuccineCookie",
    nom: "Fettuccine Cookie",
    gender: "She / It",
    role: "Defense",
    position: "Front",
    element: "Earth",
    rarity: "Epic",
    release: "4.12",
    quote: "My soul... nibbled away...",
    skill: "FettuccineCookieSkill",
  },

  {
    img: "BurntCheeseCookie",
    nom: "Burnt Cheese Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Earth",
    rarity: "Epic",
    release: "4.11",
    quote: "The pain of losing can be too great for one to bear...",
    skill: "BurntCheeseCookieSkill",
  },

  {
    img: "FrilledJellyfishCookie",
    nom: "Frilled Jellyfish Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Middle",
    element: "Water / Electricity",
    rarity: "Epic",
    release: "4.10",
    quote: "Brush and shine! Clean and bright!",
    skill: "FrilledJellyfishCookieSkill",
  },

  {
    img: "PeppermintCookie",
    nom: "Peppermint Cookie",
    gender: "They / Them",
    role: "Support",
    position: "Rear",
    element: "Water",
    rarity: "Epic",
    release: "4.9",
    quote: "Looking at the ocean feels so calm...",
    skill: "PeppermintCookieSkill",
  },

  {
    img: "BlackLemonadeCookie",
    nom: "Black Lemonade Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Electricity",
    rarity: "Epic",
    release: "4.8",
    quote: "... Like you can find time in your busy schedule?",
    skill: "BlackLemonadeCookieSkill",
  },

  {
    img: "RockstarCookie",
    nom: "Rockstar Cookie",
    gender: "He / Him",
    role: "Healing",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "4.7",
    quote: "Tons of time 'til the morning, let's make some noise!",
    skill: "RockstarCookieSkill",
  },

  {
    img: "TarteTatinCookie",
    nom: "Tarte Tatin Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "Fire",
    rarity: "Epic",
    release: "4.6",
    quote: "Stand back, I'll take care of that.",
    skill: "TarteTatinCookieSkill",
  },

  {
    img: "RoyalMargarineCookie",
    nom: "Royal Margarine Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "Poison",
    rarity: "Epic",
    release: "4.5",
    quote: "Wow, wow! Everyone, relax!",
    skill: "RoyalMargarineCookieSkill",
  },

  {
    img: "KouignAmannCookie",
    nom: "Kouign-Amann Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Light",
    rarity: "Epic",
    release: "4.4",
    quote: "Into the blessed Light!",
    skill: "KouignAmannCookieSkill",
  },

  {
    img: "PruneJuiceCookie",
    nom: "Prune Juice Cookie",
    gender: "He / Him",
    role: "Bomber",
    position: "Middle",
    element: "Poison",
    rarity: "Epic",
    release: "4.3",
    quote: "Let's admit it, every Cookie longs for fame.",
    skill: "PruneJuiceCookieSkill",
  },

  {
    img: "SpaceDoughnutCookie",
    nom: "Space Doughnut Cookie",
    gender: "They / It",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "4.2",
    quote: "Fraka-kaka-kaki...",
    skill: "SpaceDoughnutCookieSkill",
  },

  {
    img: "BlueberryPieCookie",
    nom: "Blueberry Pie Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Electricity",
    rarity: "Epic",
    release: "4.1",
    quote: "Certain things are best kept as mysteries.",
    skill: "BlueberryPieCookieSkill",
  },

  {
    img: "MilkyWayCookie",
    nom: "Milky Way Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "4.0",
    quote: "Ooh... I'll be a star!",
    skill: "MilkyWayCookieSkill",
  },

  {
    img: "ProphetCookie",
    nom: "Prophet Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "3.12",
    quote: "Ah, I've been expecting you...",
    skill: "ProphetCookieSkill",
  },

  {
    img: "PineconeCookie",
    nom: "Pinecone Cookie",
    gender: "They / Them",
    role: "Bomber",
    position: "Front",
    element: "Ice",
    rarity: "Epic",
    release: "3.11",
    quote: "*munch munch* Wha? Sugar Gnomes aren't for eating?",
    skill: "PineconeCookieSkill",
  },

  {
    img: "CarolCookie",
    nom: "Carol Cookie",
    gender: "She / Her",
    role: "Healing",
    position: "Rear",
    element: "Grass",
    rarity: "Epic",
    release: "3.10",
    quote: "A song to soothe your soul!",
    skill: "CarolCookieSkill",
  },

  {
    img: "MacaronCookie",
    nom: "Macaron Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "3.9",
    quote: "I came up with a brand new rhythm!",
    skill: "MacaronCookieSkill",
  },

  {
    img: "Schwarzwalder",
    nom: "Schwarzwälder",
    gender: "She / He / It",
    role: "Charge",
    position: "Front",
    element: "Steel / Chaos",
    rarity: "Epic",
    release: "3.8",
    quote: "Huh! Who needs Dark Enchantress Cookie when there's ME?",
    skill: "SchwarzwalderSkill",
  },

  {
    img: "CandyDiverCookie",
    nom: "Candy Diver Cookie",
    gender: "They / Them",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "3.7",
    quote: "◎■●※▲◎●!!!",
    skill: "CandyDiverCookieSkill",
  },

  {
    img: "CaptainCaviarCookie",
    nom: "Captain Caviar Cookie",
    gender: "He / Him",
    role: "Bomber",
    position: "Middle",
    element: "Water",
    rarity: "Epic",
    release: "3.6",
    quote: "If ya got something to do, just get it over with!",
    skill: "CaptainCaviarCookieSkill",
  },

  {
    img: "CreamUnicornCookie",
    nom: "Cream Unicorn Cookie",
    gender: "They / It",
    role: "Healing",
    position: "Rear",
    element: "Fire",
    rarity: "Epic",
    release: "3.4",
    quote: "Laughing together is a true marvel...",
    skill: "CreamUnicornCookieSkill",
  },

  {
    img: "FinancierCookie",
    nom: "Financier Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Light",
    rarity: "Epic",
    release: "3.3",
    quote: "I am here on a mission, not on holiday.",
    skill: "FinancierCookieSkill",
  },

  {
    img: "CrunchyChipCookie",
    nom: "Crunchy Chip Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Darkness",
    rarity: "Epic",
    release: "3.1",
    quote: "Here we come! CHARGE!",
    skill: "CrunchyChipCookieSkill",
  },

  {
    img: "WildberryCookie",
    nom: "Wildberry Cookie",
    gender: "He / Him",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "3.0",
    quote: "I will not be blinded by power.",
    skill: "WildberryCookieSkill",
  },

  {
    img: "CherryBlossomCookie",
    nom: "Cherry Blossom Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Rear",
    element: "Grass",
    rarity: "Epic",
    release: "2.9",
    quote: "Nothing better than a cup of fragrant tea!",
    skill: "CherryBlossomCookieSkill",
  },

  {
    img: "CaramelArrowCookie",
    nom: "Caramel Arrow Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Front",
    element: "Darkness",
    rarity: "Epic",
    release: "2.8",
    quote: "I will follow you, no matter how rough your path is!",
    skill: "CaramelArrowCookieSkill",
  },

  {
    img: "AffogatoCookie",
    nom: "Affogato Cookie",
    gender: "He / Him",
    role: "Bomber",
    position: "Middle",
    element: "Poison",
    rarity: "Epic",
    release: "2.7",
    quote: "The best medicine... tastes sweet in your mouth.",
    skill: "AffogatoCookieSkill",
  },

  {
    img: "TeaKnightCookie",
    nom: "Tea Knight Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "2.6",
    quote: "Survive! It is my only order.",
    skill: "TeaKnightCookieSkill",
  },

  {
    img: "EclairCookie",
    nom: "Eclair Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Middle",
    element: "None",
    rarity: "Epic",
    release: "2.6",
    quote: "Dust... dust is the enemy.",
    skill: "EclairCookieSkill",
  },

  {
    img: "CocoaCookie",
    nom: "Cocoa Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "2.5",
    quote: "He he, listening to you perform here is just like...",
    skill: "CocoaCookieSkill",
  },

  {
    img: "CottonCookie",
    nom: "Cotton Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "Grass",
    rarity: "Epic",
    release: "2.4",
    quote: "I happen to be really good with directions!",
    skill: "CottonCookieSkill",
  },

  {
    img: "PumpkinPieCookie",
    nom: "Pumpkin Pie Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Darkness",
    rarity: "Epic",
    release: "2.3",
    quote: "This calls for a celebration! We need a new dress.",
    skill: "PumpkinPieCookieSkill",
  },

  {
    img: "TwizzlyGummyCookie",
    nom: "Twizzly Gummy Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "Electricity",
    rarity: "Epic",
    release: "2.2",
    quote: "Peace? More like... PIECES!",
    skill: "TwizzlyGummyCookieSkill",
  },

  {
    img: "MalaSauceCookie",
    nom: "Mala Sauce Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "Fire",
    rarity: "Epic",
    release: "2.2",
    quote: "The Dragon's Valley counts as warm, right?",
    skill: "MalaSauceCookieSkill",
  },

  {
    img: "MoonRabbitCookie",
    nom: "Moon Rabbit Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "2.1",
    quote: "Oh I ate 'em all!",
    skill: "MoonRabbitCookieSkill",
  },

  {
    img: "RaspberryCookie",
    nom: "Raspberry Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "2.0",
    quote: "I don't believe in miracles, only hard work!",
    skill: "RaspberryCookieSkill",
  },

  {
    img: "ParfaitCookie",
    nom: "Parfait Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "1.9",
    quote: "Like, you like my toppings?! OH WOW!",
    skill: "ParfaitCookieSkill",
  },

  {
    img: "SquidInkCookie",
    nom: "Squid Ink Cookie",
    gender: "They / Them",
    role: "Magic",
    position: "Middle",
    element: "Water",
    rarity: "Epic",
    release: "1.8",
    quote: "Why... You stare...",
    skill: "SquidInkCookieSkill",
  },

  {
    img: "SorbetSharkCookie",
    nom: "Sorbet Shark Cookie",
    gender: "They / Them",
    role: "Ambush",
    position: "Middle",
    element: "Water",
    rarity: "Epic",
    release: "1.8",
    quote: "I found the best place to look at the moon in the entire kingdom!",
    skill: "SorbetSharkCookieSkill",
  },

  {
    img: "LilacCookie",
    nom: "Lilac Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Middle",
    element: "Grass",
    rarity: "Epic",
    release: "1.7",
    quote: "I never needed to look for you... You came to me yourself.",
    skill: "LilacCookieSkill",
  },

  {
    img: "MangoCookie",
    nom: "Mango Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "Water",
    rarity: "Epic",
    release: "1.6",
    quote: "All these hidden gems... And I know 'em all, ha ha!",
    skill: "MangoCookieSkill",
  },

  {
    img: "RedVelvetCookie",
    nom: "Red Velvet Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Darkness",
    rarity: "Epic",
    release: "1.5",
    quote: "I'll rip you to pieces!",
    skill: "RedVelvetCookieSkill",
  },

  {
    img: "PastryCookie",
    nom: "Pastry Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "Wind",
    rarity: "Epic",
    release: "1.4",
    quote: "Do not resist. It will only delay the inevitable.",
    skill: "PastryCookieSkill",
  },

  {
    img: "FigCookie",
    nom: "Fig Cookie",
    gender: "They / Them",
    role: "Support",
    position: "Middle",
    element: "Grass",
    rarity: "Epic",
    release: "1.4",
    quote: "Oh Cookies! Come play with me!",
    skill: "FigCookieSkill",
  },

  {
    img: "StrawberryCrepeCookie",
    nom: "Strawberry Crepe Cookie",
    gender: "They / Them",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "1.3",
    quote: "Hmmm, can GingerBrave outrun an ultrasonic missile?!",
    skill: "StrawberryCrepeCookieSkill",
  },

  {
    img: "BlackRaisinCookie",
    nom: "Black Raisin Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Middle",
    element: "Darkness",
    rarity: "Epic",
    release: "1.3",
    quote: "No point in hiding!",
    skill: "BlackRaisinCookieSkill",
  },

  {
    img: "AlmondCookie",
    nom: "Almond Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Rear",
    element: "Earth",
    rarity: "Epic",
    release: "1.2",
    quote: "Things have been quiet for some time.",
    skill: "AlmondCookieSkill",
  },

  {
    img: "LatteCookie",
    nom: "Latte Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Middle",
    element: "Earth",
    rarity: "Epic",
    release: "1.2",
    quote: "Well, well! Look who's here! Mr. Always-Busy!",
    skill: "GLatteCookieSkill",
  },

  {
    img: "CreamPuffCookie",
    nom: "Cream Puff Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "Light",
    rarity: "Epic",
    release: "1.2",
    quote: "There were times I wanted to give up... but I did it!",
    skill: "CreamPuffCookieSkill",
  },

  {
    img: "KumihoCookie",
    nom: "Kumiho Cookie",
    gender: "She / Her - It / Its (Fox)",
    role: "Charge",
    position: "Front",
    element: "Wind",
    rarity: "Epic",
    release: "1.1",
    quote: "Oh dear... You just can't get enough of me, can you?",
    skill: "KumihoCookieSkill",
  },

  {
    img: "WerewolfCookie",
    nom: "Werewolf Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Steel",
    rarity: "Epic",
    release: "1.0",
    quote: "I don't want to live with regret...!",
    skill: "WerewolfCookieSkill",
  },

  {
    img: "VampireCookie",
    nom: "Vampire Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "1.0",
    quote: "Don't worry so much.",
    skill: "VampireCookieSkill",
  },

  {
    img: "TigerLilyCookie",
    nom: "Tiger Lily Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "1.0",
    quote: "Stay... back...!",
    skill: "TigerLilyCookieSkill",
  },

  {
    img: "SparklingCookie",
    nom: "Sparkling Cookie",
    gender: "He / Him",
    role: "Healing",
    position: "Rear",
    element: "Light",
    rarity: "Epic",
    release: "1.0",
    quote: "I hope you find yourself comfortable!",
    skill: "SparklingCookieSkill",
  },

  {
    img: "SnowSugarCookie",
    nom: "Snow Sugar Cookie",
    gender: "They / Them",
    role: "Magic",
    position: "Middle",
    element: "Ice",
    rarity: "Epic",
    release: "1.0",
    quote: "I don't feel so lonely anymore!",
    skill: "SnowSugarCookieSkill",
  },

  {
    img: "RyeCookie",
    nom: "Rye Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "Fire",
    rarity: "Epic",
    release: "1.0",
    quote: "Revenge brought me here.",
    skill: "RyeCookieSkill",
  },

  {
    img: "PurpleYamCookie",
    nom: "Purple Yam Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Grass",
    rarity: "Epic",
    release: "1.0",
    quote: "Stop ASKING me random QUESTIONS!",
    skill: "PurpleYamCookieSkill",
  },

  {
    img: "PomegranateCookie",
    nom: "Pomegranate Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Middle",
    element: "Chaos",
    rarity: "Epic",
    release: "1.0",
    quote: "Once, I was foolish. Just like you.",
    skill: "PomegranateCookieSkill",
  },

  {
    img: "PoisonMushroomCookie",
    nom: "Poison Mushroom Cookie",
    gender: "They / Them",
    role: "Bomber",
    position: "Middle",
    element: "Poison / Chaos",
    rarity: "Epic",
    release: "1.0",
    quote: "Why is the sky... rotating?!",
    skill: "PoisonMushroomCookieSkill",
  },

  {
    img: "MintChocoCookie",
    nom: "Mint Choco Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Rear",
    element: "Wind",
    rarity: "Epic",
    release: "1.0",
    quote: "Just like back then...! I was thinking just the same!",
    skill: "MintChocoCookieSkill",
  },

  {
    img: "MilkCookie",
    nom: "Milk Cookie",
    gender: "He / Him",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Epic",
    release: "1.0",
    quote: "Darkness, begone!",
    skill: "MilkCookieSkill",
  },

  {
    img: "MadeleineCookie",
    nom: "Madeleine Cookie",
    gender: "He / Him",
    role: "Defense",
    position: "Front",
    element: "Light",
    rarity: "Epic",
    release: "1.0",
    quote: "Light, protect me!",
    skill: "MadeleineCookieSkill",
  },

  {
    img: "LicoriceCookie",
    nom: "Licorice Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "Darkness / Chaos / Poison",
    rarity: "Epic",
    release: "1.0",
    quote: "Clap! Applaud! MORE! MORE!",
    skill: "LicoriceCookieSkill",
  },

  {
    img: "HerbCookie",
    nom: "Herb Cookie",
    gender: "He / Him",
    role: "Healing",
    position: "Rear",
    element: "None",
    rarity: "Epic",
    release: "1.0",
    quote: "Something great is going to happen today!",
    skill: "HerbCookieSkill",
  },

  {
    img: "EspressoCookie",
    nom: "Espresso Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "Earth",
    rarity: "Epic",
    release: "1.0",
    quote: "Yes, I'm here. What now?",
    skill: "EspressoCookieSkill",
  },

  {
    img: "DarkChocoCookie",
    nom: "Dark Choco Cookie",
    gender: "He / They",
    role: "Charge",
    position: "Front",
    element: "Darkness",
    rarity: "Epic",
    release: "1.0",
    quote: "I will not fall prey so easily to the Darkness...",
    skill: "DarkChocoCookieSkill",
  },

  {
    img: "ChiliPepperCookie",
    nom: "Chili Pepper Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Middle",
    element: "Fire",
    rarity: "Epic",
    release: "1.0",
    quote: "Who ordered spicy?!",
    skill: "ChiliPepperCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // ------------------------------------------------------ SPECIALS ------------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------

  {
    img: "RumiCookie",
    nom: "Rumi Cookie",
    gender: "She / Her",
    role: "Ambush",
    position: "Front",
    element: "None",
    rarity: "Special",
    release: "7.3",
    quote: "You know together we're glowing! Gonna be, gonna be golden!",
    skill: "RumiCookieSkill",
  },

  {
    img: "MiraCookie",
    nom: "Mira Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Special",
    release: "7.3",
    quote: "Being wild is what kept me on stage.",
    skill: "MiraCookieSkill",
  },

  {
    img: "ZoeyCookie",
    nom: "Zoey Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "7.3",
    quote: "All three of us... in the bathhouse!",
    skill: "ZoeyCookieSkill",
  },

  {
    img: "ElphabaCookie",
    nom: "Elphaba Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "6.11",
    quote: "If you care to find me, look to the Western sky!",
    skill: "ElphabaCookieSkill",
  },

  {
    img: "GlindaCookie",
    nom: "Glinda Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "6.11",
    quote: "Quick, a mirror! I need to see my face.",
    skill: "GlindaCookieSkill",
  },

  {
    img: "CreamFerretCookie",
    nom: "Cream Ferret Cookie",
    gender: "They / Them",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "5.7",
    quote: "Ah, I'll never grow tired of playing all day long!",
    skill: "CreamFerretCookieSkill",
  },

  {
    img: "MarshmallowBunnyCookie",
    nom: "Marshmallow Bunny Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "6.6",
    quote: "More more more more more more!",
    skill: "MarshmallowBunnyCookieSkill",
  },

  {
    img: "IcicleYetiCookie",
    nom: "Icicle Yeti Cookie",
    gender: "They / Them",
    role: "Healing",
    position: "Front",
    element: "Ice",
    rarity: "Special",
    release: "4.14",
    quote: "A freezing winter wind follows me wherever I go!",
    skill: "IcicleYetiCookieSkill",
  },

  {
    img: "SnapdragonCookie",
    nom: "Snapdragon Cookie",
    gender: "They / It",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "4.6",
    quote: "Endt Ihn Daond!",
    skill: "SnapdragonCookieSkill",
  },

  {
    img: "JHopeCookie",
    nom: "j-hope Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "My truest wish is for everyone to have hope!",
    skill: "BTSCookieSkill",
  },

  {
    img: "JiminCookie",
    nom: "Jimin Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "I'm so glad to perform in the Cookie Kingdom!",
    skill: "BTSCookieSkill",
  },

  {
    img: "JinCookie",
    nom: "Jin Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "Let's put on a fantastic show!",
    skill: "BTSCookieSkill",
  },

  {
    img: "JungKookCookie",
    nom: "Jung Kook Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "I'll sing my heart out!",
    skill: "BTSCookieSkill",
  },

  {
    img: "RMCookie",
    nom: "RM Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "Everything is sweet and crunchy: perfect for the concert!",
    skill: "BTSCookieSkill",
  },

  {
    img: "SugaCookie",
    nom: "SUGA Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "I hope our songs can bring a smile to your face.",
    skill: "BTSCookieSkill",
  },

  {
    img: "VCookie",
    nom: "V Cookie",
    gender: "He / Him",
    role: "BTS",
    position: "Rear",
    element: "None",
    rarity: "Special",
    release: "3.8",
    quote: "You can't spell love without V!",
    skill: "BTSCookieSkill",
  },

  {
    img: "SonicCookie",
    nom: "Sonic Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "None",
    rarity: "Special",
    release: "2.1",
    quote: "Okay! Let's race!",
    skill: "SonicCookieSkill",
  },

  {
    img: "TailsCookie",
    nom: "Tails Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "None",
    rarity: "Special",
    release: "2.1",
    quote: "I calculate a disaster!",
    skill: "TailsCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // -------------------------------------------------------- RARE --------------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------

  {
    img: "CloverCookie",
    nom: "Clover Cookie",
    gender: "He / Him",
    role: "Support",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "May luck follow you in your adventures...",
    skill: "CloverCookieSkill",
  },
  {
    img: "DevilCookie",
    nom: "Devil Cookie",
    gender: "They / It",
    role: "Magic",
    position: "Middle",
    element: "Darkness",
    rarity: "Rare",
    release: "1.5",
    quote: "Soon, you will submit... Mhe he!",
    skill: "DevilCookieSkill",
  },
  {
    img: "PrincessCookie",
    nom: "Princess Cookie",
    gender: "She / Her",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "You may clap louder, hehe!",
    skill: "PrincessCookieSkill",
  },
  {
    img: "PancakeCookie",
    nom: "Pancake Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "Am I cute? Am I cute?!",
    skill: "PancakeCookieSkill",
  },
  {
    img: "OnionCookie",
    nom: "Onion Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Middle",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "Are you... hiding something?",
    skill: "OnionCookieSkill",
  },
  {
    img: "KnightCookie",
    nom: "Knight Cookie",
    gender: "He / Him",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Rare",
    release: "1.0",
    quote: "For honor!",
    skill: "KnightCookieSkill",
  },
  {
    img: "GumballCookie",
    nom: "Gumball Cookie",
    gender: "He / Him",
    role: "Bomber",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "Not glamourous enough? WHO SAID THAT?!",
    skill: "GumballCookieSkill",
  },
  {
    img: "CustardCookieIII",
    nom: "Custard Cookie III",
    gender: "He / Him",
    role: "Healing",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "We won? OH! Of course we did!",
    skill: "CustardCookieIIISkill",
  },
  {
    img: "CherryCookie",
    nom: "Cherry Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "Wanna see something fun?",
    skill: "CherryCookieSkill",
  },
  {
    img: "CarrotCookie",
    nom: "Carrot Cookie",
    gender: "She / Her",
    role: "Support",
    position: "Middle",
    element: "Grass",
    rarity: "Rare",
    release: "1.0",
    quote: "To work! Off we go!",
    skill: "CarrotCookieSkill",
  },
  {
    img: "BlackberryCookie",
    nom: "Blackberry Cookie",
    gender: "She / Her",
    role: "Magic",
    position: "Rear",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "I am the very best at my job.",
    skill: "BlackberryCookieSkill",
  },
  {
    img: "AvocadoCookie",
    nom: "Avocado Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "Steel",
    rarity: "Rare",
    release: "1.0",
    quote: "I SAW IT! YOU CHUCKLED!",
    skill: "AvocadoCookieSkill",
  },
  {
    img: "AlchemistCookie",
    nom: "Alchemist Cookie",
    gender: "She / Her",
    role: "Bomber",
    position: "Middle",
    element: "Poison",
    rarity: "Rare",
    release: "1.0",
    quote: "No miscalculations are allowed!",
    skill: "AlchemistCookieSkill",
  },
  {
    img: "AdventurerCookie",
    nom: "Adventurer Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "None",
    rarity: "Rare",
    release: "1.0",
    quote: "A new discovery is waiting!",
    skill: "AdventurerCookieSkill",
  },

  // ----------------------------------------------------------------------------------------------------------------------
  // ------------------------------------------------------- COMMON -------------------------------------------------------
  // ----------------------------------------------------------------------------------------------------------------------
  {
    img: "GingerBrave",
    nom: "GingerBrave",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "None",
    rarity: "Common",
    release: "1.0",
    quote: "Prepare to be CRUMBLED!",
    skill: "GingerbraveSkill",
  },
  {
    img: "WizardCookie",
    nom: "Wizard Cookie",
    gender: "He / Him",
    role: "Magic",
    position: "Middle",
    element: "Electricity",
    rarity: "Common",
    release: "1.0",
    quote: "Lightning strike!",
    skill: "WizardCookieSkill",
  },
  {
    img: "StrawberryCookie",
    nom: "Strawberry Cookie",
    gender: "She / Her",
    role: "Defense",
    position: "Front",
    element: "None",
    rarity: "Common",
    release: "1.0",
    quote: "Will you stay with me...?",
    skill: "StrawberryCookieSkill",
  },
  {
    img: "NinjaCookie",
    nom: "Ninja Cookie",
    gender: "He / Him",
    role: "Ambush",
    position: "Middle",
    element: "None",
    rarity: "Common",
    release: "1.0",
    quote: "The result of determined training!",
    skill: "NinjaCookieSkill",
  },
  {
    img: "MuscleCookie",
    nom: "Muscle Cookie",
    gender: "He / Him",
    role: "Charge",
    position: "Front",
    element: "Steel",
    rarity: "Common",
    release: "1.0",
    quote: "Top condition!",
    skill: "MuscleCookieSkill",
  },
  {
    img: "BeetCookie",
    nom: "Beet Cookie",
    gender: "She / Her",
    role: "Ranged",
    position: "Rear",
    element: "None",
    rarity: "Common",
    release: "1.0",
    quote: "The hunt begins!",
    skill: "BeetCookieSkill",
  },
  {
    img: "AngelCookie",
    nom: "Angel Cookie",
    gender: "They / Them",
    role: "Healing",
    position: "Rear",
    element: "None",
    rarity: "Common",
    release: "1.0",
    quote: "Light upon you...!",
    skill: "AngelCookieSkill",
  },
];
